version: "3.9"
services:
    football_players_postgres:
        image: postgres:16.2-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: football_players_db
        healthcheck:
            test: pg_isready -d postgres -U postgres
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 5s
        ports:
            - 5432:5432
        volumes:
            - football_players_volume:/var/lib/postgresql/data


volumes:
    football_players_volume:
        driver: local